[package]
name = "fanta"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
futures-util = "0.3.21"
tokio = { version = "1.17.0", features = ["full"] }
tokio-tungstenite = "0.17.1"
ctrlc = { version = "3.2.1", features = ["termination"] }
fern = { version = "0.6.1", features = ["colored"] }
clap = { version = "3.1.9", features = ["derive"] }
log = "0.4.16"
