[package]
edition = "2018"
license = "GPL-3.0-only"
name = "hulk"
version = "0.1.0"

[dependencies]
alsa = {version = "0.5.0", optional = true}
anyhow = "1.0.56"
approx = "0.5.1"
awaitgroup = "0.6.0"
base64 = "0.13.0"
byteorder = "1.4.3"
compiled-nn = "0.10.0"
ctrlc = {version = "3.2.1", features = ["termination"]}
fern = {version = "0.6.1", features = ["colored"]}
futures-util = "0.3.21"
image = "0.23.14"
libc = "0.2.123"
log = "0.4.16"
macros = {path = "macros"}
mlua = {version = "0.7.4", features = ["luajit", "serialize"], optional = true}
nalgebra = {version = "0.30.1", features = ["serde-serialize"]}
ordered-float = "2.10.0"
parking_lot = "0.12.0"
png = "0.17.5"
polling = "2.2.0"
rand = "0.8.5"
rand_distr = "0.4.3"
rustfft = "6.0.1"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
spl_network = {path = "spl_network"}
structopt = "0.3.26"
tokio = {version = "1.17.0", features = ["full"]}
tokio-tungstenite = "0.17.1"
tokio-util = "0.7.1"
uvcvideo = {path = "uvcvideo", optional = true}
v4l = {version = "0.12.1", optional = true, git = "https://github.com/HULKs/libv4l-rs", branch = "add_with_path_and_flags"}
webots = {version = "0.3.0", optional = true}

[build-dependencies]
module_attributes = {path = "module_attributes"}
petgraph = "0.6.0"
proc-macro2 = "1.0.37"
quote = "1.0.18"
syn = {version = "1.0.91", features = ["full"]}
walkdir = "2.3.2"

[features]
behavior_simulator = ["mlua"]
nao = ["uvcvideo", "v4l", "alsa"]

[[bin]]
name = "nao"
required-features = ["nao"]

[[bin]]
name = "webots"
required-features = ["webots"]

[[bin]]
name = "behavior_simulator"
required-features = ["behavior_simulator"]
