site_name: HULKs Documentation
remote_branch: docs
theme:
  name: material
  logo: logo.svg
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)" 
      primary: green
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      primary: green
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - Introduction: index.md
  - Setup:
    - Overview: setup/overview.md
    - Main Setup: setup/main_setup.md
  - Framework:
    - Overview: framework/overview.md
    - Directory Structure: framework/directory_structure.md
    - Process Entrypoint: framework/process_entrypoint.md
    - Runtime: framework/runtime.md
    - Cyclers: framework/cyclers.md
    - Modules: framework/modules.md
    - Databases & Types: framework/databases_and_types.md
    - Configuration: framework/configuration.md
    - Communication: framework/communication.md
    - Hardware Interface: framework/hardware_interface.md
    - Thread Communication: framework/thread_communication.md
    - Filtering: framework/filtering.md
    - Macros: framework/macros.md
    - Error Handling: framework/error_handling.md
    - Logging: framework/logging.md
  - Tooling:
    - Overview: tooling/overview.md
    - Pepsi: tooling/pepsi.md
  - Operating System:
    - Overview: operating_system/overview.md
  - Robotics:
    - Overview: robotics/overview.md
  - Workflow:
    - Overview: workflow/overview.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
