[package]
name = "communication"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
futures-util = "0.3.21"
log = "0.4.17"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio = { version = "1.19.2", features = ["full"] }
tokio-tungstenite = "0.17.1"
tokio-util = "0.7.3"
uuid = { version = "1.1.2", features = ["v4"] }
