[package]
edition = "2021"
license = "GPL-3.0-only"
name = "hula"
version = "0.1.0"

[dependencies]
anyhow = "1.0.58"
byteorder = "1.4.3"
chrono = "0.4.19"
clap = "3.2.6"
ctrlc = {version = "3.2.2", features = ["termination"]}
dbus = "0.9.5"
epoll = "4.3.1"
fern = "0.6.1"
hostname = "0.3.1"
ipnetwork = "0.19.0"
log = "0.4.17"
nix = "0.24.1"
pnet = "0.31.0"
pnet_datalink = "0.31.0"
regex = "1.5.6"
rmp = "0.8.11"
rmp-serde = "1.1.0"
rust-ini = "0.18.0"
serde = {version = "1.0.137", features = ["derive"]}
serde_json = "1.0.81"
systemd = "0.10.0"
