[package]
edition = "2021"
name = "hula"
version = "0.1.0"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0"
byteorder = "1.4"
chrono = "0.4"
clap = "2.33"
ctrlc = {version = "3.2", features = ["termination"]}
dbus = "0.9"
epoll = "4.3"
fern = "0.6.0"
hostname = "0.3"
log = "0.4.0"
nix = "0.23.0"
pnet = "0.28.0"
regex = "1.5"
rmp = "0.8"
rmp-serde = "0.15"
rust-ini = "0.17"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
