[package]
edition = "2021"
license = "GPL-3.0-only"
name = "hula"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
byteorder = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true }
dbus = { workspace = true }
epoll = { workspace = true }
fern = { workspace = true }
hostname = { workspace = true }
ipnetwork = { workspace = true }
log = { workspace = true }
nix = { workspace = true }
pnet = { workspace = true }
pnet_datalink = { workspace = true }
regex = { workspace = true }
rmp = { workspace = true }
rmp-serde = { workspace = true }
rust-ini = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
systemd = { workspace = true }
