[package]
edition = "2021"
license = "GPL-3.0-only"
name = "pepsi"
version = "2.0.0"

[dependencies]
anyhow = "1.0.58"
futures = "0.3.21"
nao = {path = "../../crates/nao"}
regex = "1.5.6"
repository = {path = "../../crates/repository"}
spl_network = {path = "../../crates/spl_network"}
structopt = "0.3.26"
tokio = {features = ["full"], version = "1.19.2"}
