[package]
edition = "2021"
name = "pepsi"
version = "0.1.0"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0.56"
async-std = "1.11.0"
chrono = "0.4.19"
fern = { features = ["colored"], version = "0.6.1" }
futures = { features = ["thread-pool"], version = "0.3.21" }
log = "0.4.16"
regex = "1.5.5"
serde = { features = ["derive"], version = "1.0.136" }
serde_json = "1.0.79"
structopt = "0.3.26"
tempfile = "3.3.0"
thrussh = { features = ["openssl"], version = "0.33.5" }
thrussh-keys = { features = ["openssl"], version = "0.21.0" }
tokio = { features = ["full"], version = "1.17.0" }
tokio-util = "0.7.1"
