[package]
edition = "2018"
name = "module_attributes"
version = "0.1.0"

[dependencies]
convert_case = "0.4.0"
proc-macro-error = "1.0.4"
quote = "1.0.10"
syn = {version = "1.0.82", features = ["full", "extra-traits", "visit", "visit-mut"]}
