[package]
name = "module_attributes"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
convert_case = { workspace = true }
proc-macro-error = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
